version: '3.9'

services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: solar-watch-app:latest
    ports:
      - "8080:8080"
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/solar_watch
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - codecool.app.jwtSecret=======================CodeCool=Spring===========================
      - codecool.app.jwtExpirationMs=86400000

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=solar_watch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: solar-watch-frontend:latest
    ports:
      - "5173:5173"
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
